services:
  universityapp.database:
    image: postgres:latest
    container_name: universityapp.database
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/universityapp-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - universityapp-net
        
  universityapp.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: universityapp.keycloak
    hostname: universityapp.keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://universityapp.database:5432/university
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    command: start-dev
    networks:
      - universityapp-net
        
  universityapp.rabbitmq:
    image: rabbitmq:management
    container_name: universityapp.rabbitmq
    hostname: universityapp.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - universityapp-net
  
  universityapp.userservice:
    image: universityapp.userservice
    container_name: universityapp.userservice
    build:
      context: .
      dockerfile: UniversityApp.UserService/Dockerfile
    ports:
      - "8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=universityapp.database;Database=university-users;Username=postgres;Password=postgres
      - MessageBroker__Hostname=universityapp.rabbitmq
      - MessageBroker__Port=5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - Keycloak__AuthorizationUrl=http://localhost:8080/realms/university/protocol/openid-connect/auth
      - Keycloak__TokenUrl=http://localhost:8080/realms/university/protocol/openid-connect/token
      - Authentication__DockerRealmUrl=http://universityapp.keycloak:8080/realms/university
      - Authentication__AppRealmUrl=http://localhost:8080/realms/university
      - Authentication__Audience=account
    networks:
      - universityapp-net

  universityapp.courseservice:
    image: universityapp.courseservice
    container_name: universityapp.courseservice
    build:
      context: .
      dockerfile: UniversityApp.CourseService/Dockerfile
    ports:
      - "8082"
    environment:
      - ASPNETCORE_HTTP_PORTS=8082
      - ConnectionStrings__DefaultConnection=Host=universityapp.database;Database=university-courses;Username=postgres;Password=postgres
      - MessageBroker__Hostname=universityapp.rabbitmq
      - MessageBroker__Port=5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - Keycloak__AuthorizationUrl=http://localhost:8080/realms/university/protocol/openid-connect/auth
      - Keycloak__TokenUrl=http://localhost:8080/realms/university/protocol/openid-connect/token
      - Authentication__DockerRealmUrl=http://universityapp.keycloak:8080/realms/university
      - Authentication__AppRealmUrl=http://localhost:8080/realms/university
      - Authentication__Audience=account
    networks:
      - universityapp-net

  universityapp.assignmentservice:
    image: universityapp.assignmentservice
    container_name: universityapp.assignmentservice
    build:
      context: .
      dockerfile: UniversityApp.AssignmentService/Dockerfile
    ports:
      - "8083"
    environment:
      - ASPNETCORE_HTTP_PORTS=8083
      - ConnectionStrings__DefaultConnection=Host=universityapp.database;Database=university-assignments;Username=postgres;Password=postgres
      - MessageBroker__Hostname=universityapp.rabbitmq
      - MessageBroker__Port=5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - API__CourseAPI=http://universityapp.courseservice:8082
      - API__UserAPI=http://universityapp.userservice:8081
      - Keycloak__AuthorizationUrl=http://localhost:8080/realms/university/protocol/openid-connect/auth
      - Keycloak__TokenUrl=http://localhost:8080/realms/university/protocol/openid-connect/token
      - Authentication__DockerRealmUrl=http://universityapp.keycloak:8080/realms/university
      - Authentication__AppRealmUrl=http://localhost:8080/realms/university
      - Authentication__Audience=account
    networks:
      - universityapp-net

  universityapp.apigateway:
    image: universityapp.apigateway
    container_name: universityapp.apigateway
    build:
      context: .
      dockerfile: UniversityApp.ApiGateway/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=6f003b5a-31b9-4d16-b8cd-2840a649895c
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\RStupnitskyi\.aspnet\https:/https/
    networks:
      - universityapp-net

networks:
  universityapp-net:
    driver: bridge
